language: java
sudo: required
dist: trusty
install: true
jdk: oraclejdk8
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
env:
  matrix:
  - TERM=dumb
  global:
    secure: LRj23pXG7ikrc/eJ/lcrl+KZ5R7iR1XQVlax7HI/9j6U8abYuIRi0IT34DQwcQSgZB3kXs0bWHxsIR7iz/nCH4S6bDRvImFPKwg20XMdRTbZaREx1eYPy+odXdBf/3BGbmBQ8HLrdxOVTltFWZGvvR49jScQd3z/O8k2FZln43c=
addons:
  apt:
    packages:
      - oracle-java8-installer
    organization:
      - griffon
  sonar:
    token:
      secure: i42zSa0Q9jdtAZY8MyDjTImr4ARoxpuZwm3RSVHgpC6Dg4an/eZ8PcR9/MqWYAAzxuPY/ILqnT9524bU9YoCxzVXz00k9ri41DUVRV+5TwJrQYA24Eil7bxWXWfEWWSV6zrK4jk3unir8RQrPZFIj9hsErGeC2yHI+GlSf8IBWc=
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
before_script:
  - ./gradlew --no-daemon --version
  - sudo service mysql stop
  - sudo service postgresql stop
  - sudo service acpid stop
  - sudo service atd stop
  - sudo service cron stop
  - sudo service memcached stop
  - sudo service ntp stop
  - sudo service rabbitmq-server stop
  - sudo service resolvconf stop
  - sudo service sshguard stop
  - sudo service ssh stop
script: ./gradlew --console=plain --no-daemon -S --scan check test integrationTest functionalTest jacocoTestReport jacocoIntegrationTestReport jacocoFunctionalTestReport jacocoRootReport -x :sample-javafx-groovy:jfxJar -x :sample-javafx-groovy:jfxDeploy -x :sample-javafx-java:jfxJar -x :sample-javafx-java:jfxDeploy -x clirr
after_success:
  - ./update-gh-pages.sh
  - for report in `find ./subprojects -name "jacocoTestReport.xml" -print`; do rm -f $report ; done
  - for report in `find ./samples -name "jacocoTestReport.xml" -print`; do rm -f $report; done
  - ./gradlew --no-daemon coveralls versionEyeUpdate
  - bash <(curl -s https://codecov.io/bash)
after_failure:
  - ./update-gh-pages.sh
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/914e6ffa96dfbf419d60
    on_success: change
    on_failure: always
    on_start: never
